# Generated by Django 3.1.7 on 2021-03-16 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invoice_details', models.TextField(max_length=100)),
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_details', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.TextField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Invoice_Status_Code',
            fields=[
                ('invoice_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_status_description', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Order_Item_Status_Code',
            fields=[
                ('order_item_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_item_status_description', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Order_Status_Code',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('order_status_description', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Payment_Method',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_method_name', models.CharField(max_length=30)),
                ('payment_method_code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Product_Type',
            fields=[
                ('product_type_code', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_description', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_date', models.DateField()),
                ('shipment_tracking_number', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('other_shipment_details', models.TextField(max_length=100)),
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.invoice')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.order')),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_image', models.ImageField(blank=True, upload_to='upload/user_images/')),
                ('gender', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('city', models.TextField(max_length=100)),
                ('country', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=100)),
                ('address2', models.TextField(max_length=100)),
                ('full_name', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('address1', models.TextField(max_length=100)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.order_item')),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_image', models.ImageField(upload_to='upload/product_images/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.TextField(max_length=100)),
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='order_item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.ref_order_status_code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.order'),
        ),
    ]
